-- MySQL Script generated by MySQL Workbench
-- Пт 05 фев 2021 15:03:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_force` DEFAULT CHARACTER SET utf8 ;
USE `task_force` ;

-- -----------------------------------------------------
-- Table `task_force`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`cities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `city` VARCHAR(70) NULL COMMENT 'Населенный пункт',
  `latitude` VARCHAR(15) NULL COMMENT 'Широта',
  `longitude` VARCHAR(15) NULL COMMENT 'Долгота',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = 'Населенные пункты и их координаты';


-- -----------------------------------------------------
-- Table `task_force`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `email` VARCHAR(320) NOT NULL COMMENT 'Электронная почта',
  `login` VARCHAR(70) NOT NULL COMMENT 'Логин',
  `password` VARCHAR(255) NOT NULL COMMENT 'Пароль',
  `date_add` DATETIME NULL COMMENT 'Дата создания аккаунта',
  `city_id` INT UNSIGNED NOT NULL COMMENT 'id населенного пункта',
  `avatar` VARCHAR(70) NULL DEFAULT NULL COMMENT 'Аватар',
  `birthday` DATETIME NULL DEFAULT NULL COMMENT 'Дата рождения',
  `about_me` TEXT NULL DEFAULT NULL COMMENT 'О пользователе',
  `phone` VARCHAR(11) NULL DEFAULT NULL COMMENT 'Телефон',
  `skype` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Skype',
  `telegram` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Telegram',
  `raiting` DECIMAL UNSIGNED NULL DEFAULT NULL COMMENT 'Рейтинг',
  `last_activity` DATETIME NULL DEFAULT NULL COMMENT 'Дата последней активности',
  `is_builder` TINYINT(1) NULL DEFAULT 0 COMMENT 'Признак испольнителя',
  `new_message` TINYINT(1) NULL DEFAULT 1 COMMENT 'Новое сообщение',
  `task_actions` TINYINT(1) NULL DEFAULT 1 COMMENT 'Действия по заданию',
  `new_review` TINYINT(1) NULL DEFAULT 1 COMMENT 'Новый отзыв',
  `show_my_contacts` TINYINT(1) NULL DEFAULT 1 COMMENT 'Показывать мои контакты только заказчику',
  `not_show_my_profile` TINYINT(1) NULL DEFAULT 1 COMMENT 'Не показывать мой профиль',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_cities_idx` (`city_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_users_cities`
    FOREIGN KEY (`city_id`)
    REFERENCES `task_force`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Пользователи';


-- -----------------------------------------------------
-- Table `task_force`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `category` VARCHAR(70) NULL COMMENT 'Наименование категории',
  `icon` VARCHAR(70) NULL COMMENT 'Иконка',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = 'Категории заданий';


-- -----------------------------------------------------
-- Table `task_force`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`photos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'user id ',
  `name` VARCHAR(70) NULL COMMENT 'Название фото',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_photos_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_photos_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Фотографии выполненных работ исполнителей';


-- -----------------------------------------------------
-- Table `task_force`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `date_add` DATETIME NULL COMMENT 'Дата добавления',
  `customer_id` INT UNSIGNED NOT NULL COMMENT 'id заказчика',
  `builder_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'id исполнителя',
  `job` VARCHAR(255) NULL COMMENT 'Краткое описание работы',
  `description` TEXT NULL COMMENT 'Подробности задания',
  `category_id` INT UNSIGNED NOT NULL COMMENT 'id категории работ',
  `address` VARCHAR(255) NULL COMMENT 'Адрес исполнения',
  `cities_id` INT UNSIGNED NOT NULL COMMENT 'id населенного пункта',
  `latitude` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Широта',
  `longitude` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Долгота',
  `budget` INT UNSIGNED NULL DEFAULT 0 COMMENT 'Бюджет',
  `date_expire` DATETIME NULL DEFAULT NULL COMMENT 'Дата исполнения',
  `status` VARCHAR(45) NULL COMMENT 'Статус задания',
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_users1_idx` (`customer_id` ASC),
  INDEX `fk_tasks_users2_idx` (`builder_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tasks_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users2`
    FOREIGN KEY (`builder_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `task_force`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Задания';


-- -----------------------------------------------------
-- Table `task_force`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `task_id` INT UNSIGNED NOT NULL COMMENT 'id задания',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_files_tasks_idx` (`task_id` ASC),
  CONSTRAINT `fk_files_tasks`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Файлы заданий';


-- -----------------------------------------------------
-- Table `task_force`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`responses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `date_add` DATETIME NULL COMMENT 'Дата добавления',
  `task_id` INT UNSIGNED NOT NULL COMMENT 'id задания',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id исполнителя',
  `cost` INT UNSIGNED NULL DEFAULT 0 COMMENT 'Предлагаемая стоимоть работы',
  `comment` TEXT NULL COMMENT 'Комментарий',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_responses_tasks_idx` (`task_id` ASC),
  INDEX `fk_responses_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_responses_tasks`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Отклики на задания';


-- -----------------------------------------------------
-- Table `task_force`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`favorites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id_customer` INT UNSIGNED NOT NULL COMMENT 'id заказчика',
  `user_id_builder` INT UNSIGNED NOT NULL COMMENT 'id исполнителя',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_favorites_users1_idx` (`user_id_customer` ASC),
  INDEX `fk_favorites_users2_idx` (`user_id_builder` ASC),
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`user_id_customer`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_users2`
    FOREIGN KEY (`user_id_builder`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Избранные исполнители';


-- -----------------------------------------------------
-- Table `task_force`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `task_id` INT UNSIGNED NOT NULL COMMENT 'id задания',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id пользователя',
  `date_add` DATETIME NULL COMMENT 'Дата добавления',
  `message` TEXT NULL COMMENT 'Сообщение',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_messages_tasks_idx` (`task_id` ASC),
  INDEX `fk_messages_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_messages_tasks`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Сообщения пользователей';


-- -----------------------------------------------------
-- Table `task_force`.`opinions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`opinions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id исполнителя',
  `task_id` INT UNSIGNED NOT NULL COMMENT 'id задания',
  `review_author_id` INT UNSIGNED NOT NULL COMMENT 'id заказчика',
  `date_add` DATETIME NULL COMMENT 'Дата добавления',
  `rating` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Оценка',
  `description` TEXT NULL COMMENT 'Отзыв',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_opinions_users1_idx` (`user_id` ASC),
  INDEX `fk_opinions_tasks_idx` (`task_id` ASC),
  INDEX `fk_opinions_users2_idx` (`review_author_id` ASC),
  CONSTRAINT `fk_opinions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opinions_tasks`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opinions_users2`
    FOREIGN KEY (`review_author_id`)
    REFERENCES `task_force`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Отзывы о качестве работы исполнителей';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
